Features/integrate pypsa eur
openego/powerd-data pull request #122
Opened 2023-09-14 11:58 UTC by ClaraBuettner

This branch updates the integration of pypsa-eur (which is now used instead of pypsa-eur-sec). 
Changes for pypsa-eur are now done within powerd-data, so we do not need a fork from pypsa-eur anymore. 

## Before merging into `dev`-branch, please make sure that

- [ ] the `CHANGELOG.rst` was updated.
- [ ] new and adjusted code is formated using `black` and `isort`.
- [ ] the `Dataset`-version is updated when existing datasets are adjusted.
- [ ] the branch was merged into the
      `continuous-integration/run-everything-over-the-weekend`-branch.
- [ ] the workflow is running successful in `test mode`.
- [ ] the workflow is running successful in `Everything` mode.

2023-09-27 09:05 UTC, ClaraBuettner commented on src/egon/data/datasets/pypsaeur/__init__.py
> +from egon.data.datasets.pypsaeur.manipulate_prepared_network import execute
@ulfmueller This line runs into errors

2023-09-27 09:05 UTC, ClaraBuettner commented on src/egon/data/datasets/pypsaeur/manipulate_prepared_network.py
> +def execute():
@ulfmueller. The function is defined here

2024-04-18 14:01 UTC, CarlosEpia commented
I installed powerd-data using this branch and started a new calculation for the status2019 scenario. Below you can find relevant information:
-airflow-port: 8081
-database-name: powerd-data
-database-port: '59731'
- working directory: home/powerd/powerd-run-de
- virtual environment: home/powerd/powerd-run-de/venv
- git repository: home/powerd/powerd-run-de/powerd-data

2024-04-18 14:02 UTC, CarlosEpia commented
Airflow starts but the same error is displayed for both pipelines:

Broken DAG: [/home/powerd/powerd-run-de/powerd-data/src/egon/data/airflow/dags/pipeline_status_quo.py]
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/powerd/powerd-run-de/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 56, in <module>
    from airflow.utils.file import get_unique_dag_module_name
ImportError: cannot import name 'get_unique_dag_module_name' from 'airflow.utils.file' (/home/powerd/powerd-run-de/venv/lib/python3.8/site-packages/airflow/utils/file.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/powerd/powerd-run-de/powerd-data/src/egon/data/datasets/__init__.py", line 12, in <module>
    from airflow.operators.python_operator import PythonOperator
  File "/home/powerd/powerd-run-de/venv/lib/python3.8/site-packages/airflow/utils/deprecation_tools.py", line 63, in getattr_with_deprecation
    raise ImportError(error_message) from e
ImportError: Could not import `airflow.operators.python.PythonOperator` while trying to import `airflow.operators.python_operator.PythonOperator`.

2024-05-13 13:14 UTC, ClaraBuettner commented
> Airflow starts but the same error is displayed for both pipelines:
> 
> Broken DAG: [/home/powerd/powerd-run-de/powerd-data/src/egon/data/airflow/dags/pipeline_status_quo.py] Traceback (most recent call last): File "", line 219, in _call_with_frames_removed File "/home/powerd/powerd-run-de/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 56, in from airflow.utils.file import get_unique_dag_module_name ImportError: cannot import name 'get_unique_dag_module_name' from 'airflow.utils.file' (/home/powerd/powerd-run-de/venv/lib/python3.8/site-packages/airflow/utils/file.py)
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "/home/powerd/powerd-run-de/powerd-data/src/egon/data/datasets/**init**.py", line 12, in from airflow.operators.python_operator import PythonOperator File "/home/powerd/powerd-run-de/venv/lib/python3.8/site-packages/airflow/utils/deprecation_tools.py", line 63, in getattr_with_deprecation raise ImportError(error_message) from e ImportError: Could not import `airflow.operators.python.PythonOperator` while trying to import `airflow.operators.python_operator.PythonOperator`.

Thanks for reporting! I can somehow not reproduce the problem locally. Does the environment still exist on the server?

2024-05-13 13:25 UTC, ClaraBuettner commented
Since the problem looked like #218, I merged that branch.
If it solves the problem, I will merge the other PR.

2024-05-13 13:25 UTC, CarlosEpia commented
> > Airflow starts but the same error is displayed for both pipelines:
> > Broken DAG: [/home/powerd/powerd-run-de/powerd-data/src/egon/data/airflow/dags/pipeline_status_quo.py] Traceback (most recent call last): File "", line 219, in _call_with_frames_removed File "/home/powerd/powerd-run-de/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 56, in from airflow.utils.file import get_unique_dag_module_name ImportError: cannot import name 'get_unique_dag_module_name' from 'airflow.utils.file' (/home/powerd/powerd-run-de/venv/lib/python3.8/site-packages/airflow/utils/file.py)
> > The above exception was the direct cause of the following exception:
> > Traceback (most recent call last): File "/home/powerd/powerd-run-de/powerd-data/src/egon/data/datasets/**init**.py", line 12, in from airflow.operators.python_operator import PythonOperator File "/home/powerd/powerd-run-de/venv/lib/python3.8/site-packages/airflow/utils/deprecation_tools.py", line 63, in getattr_with_deprecation raise ImportError(error_message) from e ImportError: Could not import `airflow.operators.python.PythonOperator` while trying to import `airflow.operators.python_operator.PythonOperator`.
> 
> Thanks for reporting! I can somehow not reproduce the problem locally. Does the environment still exist on the server?
Sure. Everything related to this test is still available in at31:
-airflow-port: 8081
-database-name: powerd-data
-database-port: '59731'

working directory: home/powerd/powerd-run-de
virtual environment: home/powerd/powerd-run-de/venv
git repository: home/powerd/powerd-run-de/powerd-data

2024-05-17 13:15 UTC, ClaraBuettner commented
@CarlosEpia: I am very optimistic that pypsa-eur will finish now successfully. There were some problems with downloading files (inside pypsa-eur). I tried to fix this by copying some files, which is not the best solution (I'm sorry!).
 In general, the download works fine when I test it locally, so it might be related to the server. 

I run pypsa-eur outside of airflow to speed up the bug fixing. But I think you can now either restart the task "pypsa_eur.prepare_network" or just mark it as successful as it was already running in a separate process. 
At least it is possible now to continue running the pipeline. I wish I would have been able to do a complete run before I leave. But I hope it also works out like this and you can continue from this point on.

2024-05-24 09:09 UTC, CarlosEpia commented
There are several references in the function `execute` to files that are not available:
- "data_bundle_powerd_data/district_heating_shares_egon.csv"
- "input-pypsa-eur-sec/heat_demand_timeseries_DE_eGon100RE.csv"
- "input-pypsa-eur-sec/electrical_demand_timeseries_DE_eGon100RE.csv"
- "input-pypsa-eur-sec/geothermal_potential_germany.csv"

2024-05-27 13:08 UTC, CarlosEpia requested changes
At the end, it was not possible to run these tasks locally or on the server. I also tried to use the pre-network already generated but the next tasks failed as well.

2024-05-27 13:08 UTC, CarlosEpia commented on src/egon/data/datasets/pypsaeur/__init__.py
> +        __path__[0] + "/datasets/pypsaeursec/config.yaml", "r"
Do you mean `__path__[0] + "/datasets/pypsaeur/config.yaml", "r"` ?

2024-05-27 13:08 UTC, CarlosEpia commented on src/egon/data/datasets/pypsaeur/__init__.py
> +        shutil.copy(
There is a problem with this command. I adjusted it in the commit 70e27dd and then it worked.

2024-05-29 07:57 UTC, CarlosEpia commented
The tasks included in the new class `RunPypsaEur` must be included as a dependency for `ElectricalNeighbours`

2024-06-12 10:51 UTC, ClaraBuettner commented
Some of the missing files are created when eGon100RE is one of the selected scenarios. One file needs to be added to the data bundle and in one other case, I need to have a look at the code. 
But at least it works when the missing files are added manually.

2024-06-12 14:16 UTC, ClaraBuettner commented
> The tasks included in the new class `RunPypsaEur` must be included as a dependency for `ElectricalNeighbours`

That is strange, the prepared network should be enough. That is already part of the dependencies. Do you remember which error you got?

2024-06-16 17:41 UTC, CarlosEpia commented
I copy pasted the file Snakefile from your session in order to get the over this problem: Error: Snakefile "run-pypsa-eur/Snakefile" not found.; 331359)

2024-08-20 07:54 UTC, ClaraBuettner commented
This PR was replaced by the (already merged) PR #293

2024-08-20 07:54 UTC, closed without merging